name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pr-title-check:
    name: PR Title Check
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04

    steps:
      - name: Check PR Title
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.pull_request.title;
            const pattern = /(^[mM]erge\s.*$)|(^[rR]evert\s.*$)|(^BREAKING CHANGE:.*$)|(^MINOR\s.*$)|(^(\w+)(?:\(([\w\$\.\-\*\s]+)\))?\:\s(.+)$)/;
            if (!pattern.test(title)) {
              core.setFailed(`PR title "${title}" doesn't match required format. Please use one of:
              - Conventional commit format: "type(scope): description"
              - Merge format: "Merge ..."
              - Revert format: "Revert ..."
              - Breaking change: "BREAKING CHANGE: description"
              - Minor change: "MINOR description"`);
            }

  build:
    name: ${{ matrix.os }} Build and Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19 all

          sudo apt-get install -y --no-install-recommends \
            build-essential cmake curl libcurl4-openssl-dev zlib1g-dev \
            libzstd-dev libsnappy-dev ccache clang-format-19

      - name: Install System Dependencies (macOS)
        if: matrix.os == 'macos-14'
        run: brew install ccache

      - name: Set up specific CMake version (macOS)
        if: matrix.os == 'macos-14'
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.28.3'

      - name: Set up ccache
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            echo "CCACHE_DIR=/home/runner/.ccache" >> $GITHUB_ENV
            echo "/usr/lib/ccache" >> $GITHUB_PATH
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            echo "CCACHE_DIR=/Users/runner/Library/Caches/ccache" >> $GITHUB_ENV
            echo "/opt/homebrew/opt/ccache/libexec" >> $GITHUB_PATH
          fi

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.CCACHE_DIR }}
            build/_deps

          key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Check C++ Code Style
        if: matrix.os == 'ubuntu-22.04'
        run: |
          find src/ include/ -name '*.cpp' -o -name '*.hpp' | xargs clang-format-19 --dry-run -Werror

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DLOAD_TESTS=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Install GraphAr CLI and Generate Data
        if: matrix.os == 'ubuntu-22.04'
        run: |
          set -euxo pipefail
          pip3 install --upgrade pip

          # Install GraphAr CLI (simplified script)
          ROOT_DIR=$(pwd)
          DEPS_DIR=$ROOT_DIR/build/_deps
          ARROW_INSTALL_DIR=$DEPS_DIR/arrow-install
          ARROW_BUILD_DIR=$DEPS_DIR/arrow-prefix/src/arrow-build
          PROTOBUF_INSTALL_DIR=$ARROW_BUILD_DIR/protobuf_ep-install
          GRAPHAR_CLI_DIR=$DEPS_DIR/graphar-prefix/src/graphar/cli

          CMAKE_ARGS=(
            --config-settings=cmake.define.Arrow_DIR="$ARROW_INSTALL_DIR/lib/cmake/Arrow"
            --config-settings=cmake.define.Parquet_DIR="$ARROW_INSTALL_DIR/lib/cmake/Parquet"
            --config-settings=cmake.define.ArrowDataset_DIR="$ARROW_INSTALL_DIR/lib/cmake/ArrowDataset"
            --config-settings=cmake.define.ArrowAcero_DIR="$ARROW_INSTALL_DIR/lib/cmake/ArrowAcero"
            --config-settings=cmake.define.Protobuf_INCLUDE_DIR="$PROTOBUF_INSTALL_DIR/include"
            --config-settings=cmake.define.Protobuf_LIBRARIES="$PROTOBUF_INSTALL_DIR/lib/libprotobuf.a"
            --config-settings=cmake.define.CMAKE_INSTALL_RPATH_USE_LINK_PATH=ON
          )
          pip3 install "$GRAPHAR_CLI_DIR" "${CMAKE_ARGS[@]}"

          GRAPH_DIR=$ROOT_DIR/data/snap-musae-github
          GRAPH_IMPORT_TEMPLATE=$GRAPH_DIR/import.script.git.yaml
          GRAPH_IMPORT=$GRAPH_DIR/import.git.yaml
          GRAPH_RESULT_DIR=$GRAPH_DIR/graphar
          mkdir -p "$GRAPH_RESULT_DIR"
          cp "$GRAPH_IMPORT_TEMPLATE" "$GRAPH_IMPORT"
          sed -i "s|\$DIR_PATH|$GRAPH_DIR|g" "$GRAPH_IMPORT"
          graphar import -c "$GRAPH_IMPORT"
          rm "$GRAPH_IMPORT"

      - name: Run Unit Tests
        if: matrix.os == 'ubuntu-22.04'
        run: build/_deps/duckdb-build/test/unittest "[graphar]" --reporter console

      - name: Prepare Artifacts for Upload
        run: |
          mkdir -p upload-artifacts

          cp build/_deps/duckdb-build/duckdb upload-artifacts/
          cp build/_deps/duckdb-build/extension/duckdb_graphar/duckdb_graphar.duckdb_extension upload-artifacts/

          if [ "${{ matrix.os }}" == "macos-14" ]; then
            cp ./build/_deps/arrow-install/lib/libarrow.1900.dylib upload-artifacts/
            cp ./build/_deps/arrow-install/lib/libarrow_dataset.1900.dylib upload-artifacts/
            cp ./build/_deps/arrow-install/lib/libarrow_acero.1900.dylib upload-artifacts/
            cp ./build/_deps/arrow-install/lib/libparquet.1900.dylib upload-artifacts/

            cp ./build/_deps/graphar-install/lib/libgraphar.dylib upload-artifacts/
          else
            cp ./build/_deps/arrow-install/lib/libarrow.so.1900 upload-artifacts/
            cp ./build/_deps/arrow-install/lib/libarrow_dataset.so.1900 upload-artifacts/
            cp ./build/_deps/arrow-install/lib/libarrow_acero.so.1900 upload-artifacts/
            cp ./build/_deps/arrow-install/lib/libparquet.so.1900 upload-artifacts/

            cp ./build/_deps/graphar-install/lib/libgraphar.so upload-artifacts/
          fi

          cat <<'EOF' > upload-artifacts/run_duckdb.sh
          #!/bin/bash
          SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
          if [[ "$(uname)" == "Darwin" ]]; then
            export DYLD_LIBRARY_PATH="$SCRIPT_DIR:$DYLD_LIBRARY_PATH"
          else
            export LD_LIBRARY_PATH="$SCRIPT_DIR:$LD_LIBRARY_PATH"
          fi
          "$SCRIPT_DIR/duckdb" "$@"
          EOF
          chmod +x upload-artifacts/run_duckdb.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: duckdb-graphar-${{ matrix.os }}
          path: upload-artifacts
